# Site settings
title: Kanawish.com
email: etienne.caron@gmail.com
url: https://kanawish.com
description: "Site covering my talks, projects and such."
skills: "<p>Mobile Development <p>Client-Server Architecture <p>Embedded Software Development <p>Software Design"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  8BC34A #80B3FF
  primary-rgb: "124,288,156" #"128,179,255"
  secondary: 689F38 #FD6E8A
  secondary-dark: 8BC34A #CDDC39 #233140 #A2122F

# Footer settings
footer:
  copyright: Etienne Caron
  location: Montreal
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/kanawish
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/kanawish

# Postal address (add as many lines as necessary)
address:
  - line: 5039 16th Avenue
  - line: Montreal, QC 
  - line: H1X 2S1 
  - line: Canada

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
